apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapp
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginapp
  template:
    metadata:
      labels:
        app: loginapp
    spec:
      hostAliases:
        - ip: "172.18.18.11"
          hostnames:
            - "dex.k8s.ipademo.local"
      containers:
      - image: objectiflibre/login-app:latest
        name: loginapp
#        command:
#          - sleep
#        args:
#          - "86400"
        ports:
        - name: http
          containerPort: 5555
        volumeMounts:
        - name: ca
          mountPath: /etc/ssl/
        - name: config
          mountPath: /app/
        - name: tls
          mountPath: /etc/loginapp/tls
      volumes:
      - name: ca
        configMap:
          name: ca
          items:
          - key: ca.pem
            path: ca.pem
      - name: config
        configMap:
          name: loginapp
          items:
          - key: config.yaml
            path: config.yaml
      - name: tls
        secret:
          secretName: login.k8s.ipademo.local.tls
